### ISSUE TITLE
Replace temp files with StringIO buffer

### ISSUE THREAD

**Issue by SamProtas** [afg419/journal#36]
During the download process you're saving journal entires to a temp file, reading the temp file into memory, then deleting the temp file. This leaves the potential for errors to leave "straggler temp files" behind on your server as well as not being very performant.

Google has a good example on their website of a way to avoid this and keep the contents in memory (safer and faster).

https://developers.google.com/drive/v2/web/manage-downloads#examples

```
def download_file(client, file)
  buffer = StringIO.new
  begin
    client.get_file(file.id, download_dest: buffer)
    return buffer.to_s
  rescue Google::Apis::Error => e
    puts "Unable to download file: #{e.message}"
    return nil
  end
end
```

Note how a `StringIO` object is used as a sort of "in memory file" as the download destination. No disk IO (slow) and no way leftover journal entries end up on your server.

**Comment by afg419** [comment]
Whoa.  I though I had invented that work around from scratch.  This seems much better.
